//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;

    public partial class Product
    {
        public int Id { get; set; }
        public string Product_Name { get; set; }
        public string Product_Description { get; set; }
        public Nullable<int> Price { get; set; }
        
        [DisplayName("Product image")]
        public string FileName { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
